# Generated by Django 4.0.1 on 2022-02-04 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_commensal_creation_time_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commensal',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 8, 49, 44, 527783), verbose_name='creation time'),
        ),
    ]
