# Generated by Django 4.0.1 on 2022-02-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_alter_commensal_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commensal',
            name='creation_time',
            field=models.DateTimeField(verbose_name='creation time'),
        ),
    ]
