# Generated by Django 4.0.1 on 2022-03-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_rename_commensal_meal_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('day', 'user', 'meal_type'), name='one_meal_per_person'),
        ),
    ]
