# Generated by Django 4.0.1 on 2022-02-03 16:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_commensal_creation_time_commensal_family_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commensal',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 17, 25, 30, 82576), verbose_name='creation time'),
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('meal_type', models.CharField(default='', max_length=50)),
                ('commensal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.commensal')),
            ],
        ),
    ]
