# Generated by Django 4.0.1 on 2022-02-04 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_commensal_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='commensal',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 16, 39, 4, 900276), verbose_name='creation time'),
        ),
        migrations.DeleteModel(
            name='Meals',
        ),
        migrations.AddField(
            model_name='meal',
            name='commensal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.commensal'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mealtype'),
        ),
    ]
