# Generated by Django 4.0.1 on 2022-03-14 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0013_alter_commensal_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='commensal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('BR', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner')], default='BR', max_length=2),
        ),
        migrations.DeleteModel(
            name='Commensal',
        ),
        migrations.DeleteModel(
            name='MealType',
        ),
    ]
