# Generated by Django 4.0.1 on 2022-09-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0017_alter_meal_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('BR', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner')], default='LU', max_length=2),
        ),
    ]
